//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_type
    {
        public System.Guid id { get; set; }
        public short type_documents { get; set; }
        public string nombre { get; set; }
        public short codigo_addenda { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
